---
final_name: statsd-injector
min_cli_version: 1.5.0.pre.1001
blobstore:
  provider: s3
  options:
    bucket_name: statsd-injector-release-blobs
    region: us-east-1
    endpoint: https://s3-us-east-1.amazonaws.com
